build:
  maxIssues: 40

style:
  active: true
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  UnusedPrivateMember:
    active: true

complexity:
  active: true
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 10
  LongMethod:
    active: true
    threshold: 60
  LargeClass:
    active: true
    threshold: 600

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false

comments:
  active: true
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  OutdatedDocumentation:
    active: false

naming:
  active: true
  MemberNameEqualsClassName:
    active: false
  PackageNaming:
    active: true
    packagePattern: "[a-z_]+(\\.[a-z_][a-zA-Z0-9_]*)*"
  FunctionNaming:
    active: false

performance:
  active: true

potential-bugs:
  active: true
  IgnoredReturnValue:
    active: false
